config/routes.rb
Wedding::Application.routes.draw do
  get "static_pages/home"

  get "static_pages/help"

  resources :microposts

  resources :users

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  attr_accessible :content, :user_id
  
  belongs_to :user
  
  validates :content, :length => { :maximum => 140 }
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :address, :attending, :comments, :name, :nights
  has_many :microposts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  # GET /microposts
  # GET /microposts.json
  def index
    @microposts = Micropost.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @microposts }
    end
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show
    @micropost = Micropost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @micropost }
    end
  end

  # GET /microposts/new
  # GET /microposts/new.json
  def new
    @micropost = Micropost.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @micropost }
    end
  end

  # GET /microposts/1/edit
  def edit
    @micropost = Micropost.find(params[:id])
  end

  # POST /microposts
  # POST /microposts.json
  def create
    @micropost = Micropost.new(params[:micropost])

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to @micropost, notice: 'Micropost was successfully created.' }
        format.json { render json: @micropost, status: :created, location: @micropost }
      else
        format.html { render action: "new" }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /microposts/1
  # PUT /microposts/1.json
  def update
    @micropost = Micropost.find(params[:id])

    respond_to do |format|
      if @micropost.update_attributes(params[:micropost])
        format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost = Micropost.find(params[:id])
    @micropost.destroy

    respond_to do |format|
      format.html { redirect_to microposts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Your information has been saved!' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'Your details were successfully updated. Thanks!' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Joseph & Tandra | Forever</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/microposts/_form.html.erb
<%= form_for(@micropost) do |f| %>
  <% if @micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% @micropost.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/microposts/edit.html.erb
<h1>Editing micropost</h1>

<%= render 'form' %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

app/views/microposts/index.html.erb
<h1>Listing microposts</h1>

<table>
  <tr>
    <th>Content</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @microposts.each do |micropost| %>
  <tr>
    <td><%= micropost.content %></td>
    <td><%= micropost.user_id %></td>
    <td><%= link_to 'Show', micropost %></td>
    <td><%= link_to 'Edit', edit_micropost_path(micropost) %></td>
    <td><%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Micropost', new_micropost_path %>

app/views/microposts/new.html.erb
<h1>New micropost</h1>

<%= render 'form' %>

<%= link_to 'Back', microposts_path %>

app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @micropost.content %>
</p>

<p>
  <b>User:</b>
  <%= @micropost.user_id %>
</p>


<%= link_to 'Edit', edit_micropost_path(@micropost) %> |
<%= link_to 'Back', microposts_path %>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<!DOCTYPE html>
<html>
  <head>
    <title>Ruby on Rails Tutorial Sample App | <%= yield(:title) %></title>
  </head>
  <body>
    <h1>Help</h1>
    <p>
      Get help on the Ruby on Rails Tutorial at the
      <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
      To get help on this sample app, see the
      <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
    </p>
  </body>
</html>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<!DOCTYPE html>
<html>
  <head>
    <title>Ruby on Rails Tutorial Sample App | <%= yield(:title) %></title>
  </head>
  <body>
    <h1>Sample App</h1>
    <p>
      This is the home page for the
      <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
      sample application.
    </p>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Name" %><br />
    <%= f.text_field :name %><br />
  </div>
  <div class="field">
    <%= f.label :attending, "Will you be attending the wedding?" %><br />
    <%= f.radio_button :attending, true %>
    <%= f.label :attending, "Yes", :value => true %><br />
    <%= f.radio_button :attending, false %>
    <%= f.label :attending, "No", :value => false %><br /><br />
  </div>
  <div class="field">
    If yes, please enter the following.<br /><br />
    <%= f.label :address, "Mailing Address:" %><br />
    <%= f.text_area :address, :cols => 20, :rows => 3  %><br />
  </div>
  <div class="field">
    <%= f.label :nights, "Which nights will you be staying at the hostel?" %><br />
    <%= f.radio_button :nights, 0 %>
    <%= f.label :nights, "Friday, 6/28", :value => 0 %> <br />
    <%= f.radio_button :nights, 1 %> 
    <%= f.label :nights, "Saturday, 6/29", :value => 1 %> <br />
    <%= f.radio_button :nights, 2 %>
    <%= f.label :nights, "Both!", :value => 2 %><br />
    <%= f.radio_button :nights, 3 %>
    <%= f.label :nights, "Neither", :value => 3 %><br />
  </div>
  <div class="field">
    <%= f.label :comments, "Any questions or comments?" %><br />
    <%= f.text_area :comments, :cols => 20, :rows => 3%><br />
  </div>
  <div class="actions">
    <%= f.submit "Submit"%>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit your information.</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<div class="gandalph">
  <p><input type="text" name="moria" id="moria"/><br />
  <button type="button" id="mines" onclick="moria()">Ennyn Durin aran Moria. Pedo mellon a minno</button></p>
</div>

<div id="the_mine">
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Attending</th>
    <th>Address</th>
    <th>Nights</th>
    <th>Comments</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.attending %></td>
    <td><%= user.address %></td>
    <td><%= user.nights %></td>
    <td><%= user.comments %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>
</div>
<script>
  // this is the div to hide
  var div = document.getElementById('the_mine');

  //hide the div - this should be done in CSS
  div.style.display = "none";

  //get value of the text field
  var tolken =document.getElementById("moria").value;

  // evaluate submission
  function moria() {
  var tolken =document.getElementById("moria").value;
  if (tolken == "buddy")
  	  {
  	  div.style.display = "block";
  	  }
  	else 
  	  {
  		div.style.display = "none";
  	  }
  }
</script>

app/views/users/new.html.erb
<% provide(:title, 'Tandra and Joseph | FOREVER') %>
<!DOCTYPE html>
<html>
<head>
  <title>Joseph and Tandra | <%= yield(:title) %></title>
</head>
<body>
  <div id="main_container">
    <div id="pics">
      <%= image_tag "lighthouse.jpeg" %>
      <div id="banner_text">
        <h1>Tandra and Joseph are getting married!!</h1>
      </div>
      <div id="details">
        <p>June 29th, 2013 in the <a href="http://www.parksconservancy.org/visit/park-sites/marin-headlands.html" target="_blank">Marin Headlands</a></p>
      </div>
      <div id="form_inputs">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/users/show.html.erb
<script type="text/javascript" src="//use.typekit.net/kxw8lwr.js"></script>
<script type="text/javascript">try{Typekit.load();}catch(e){}</script>

<!-- <style type="text/css">
</style> -->



<body id="power">
<h1 id="deet1"><%= notice %></h1>
<img id="deet3" src="/assets/home.jpg"/>
<p id="deet2">Email us at <a id="deet4" href="mailto:tandra.froehlich@gmail.com">tandra.froehlich@gmail.com</a> if you have any questions or have a change of plans. Thanks!</p>

<p id="deet2"><%= link_to 'Edit info', edit_user_path(@user), :id => 'deet4' %></p>
</body>